name: Install
description: Checks out the repo, sets up node using .nvmrc, installs all dependencies, caches dependencies

runs:
  using: 'composite'
  steps:
    - name: Read .nvmrc
      id: nvm
      shell: bash
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}

    - name: Install Dependencies
      shell: bash
      run: yarn install --frozen-lockfile
